apiVersion: v1
kind: Pod
metadata:
  name: simpleapp
  labels:
    env: development
spec:
  containers:
  - name: simpleapp
    image: howtoautomateinth/docker-simpleapp:v1.1
    ports:
    - containerPort: 5000